version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-network

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - redis-network

  minio:
    container_name: minio
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: admin123
    command: server --console-address ":9001" /data

networks:
  redis-network:
    driver: bridge
  mongo-network:
    driver: bridge

volumes:
  minio_storage: {}