version: '3'

networks:
  app-tier:
    driver: bridge

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier