version: '1'

networks:
  app-tier:
    driver: bridge

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Api@pass!"
      ACCEPT_EULA: "Y"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
